version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.4
    container_name: nexusland_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nexusland
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgis_data:
